"""🧬 Tam klon üçün hazırla — `ai-website-cloner` sənədləri.

`ai-website-cloner` proqram deyil, Claude Code skill-idir (`/clone-website`).
Ona görə SaytLupa klonu özü qurmur — skill-in `INSPECTION_GUIDE.md`-də tələb
etdiyi `docs/research/*.md` sənədlərini **hazırlayır**, tam işi Claude Code görür.

Sənədlər ingiliscədir: onları oxuyan tərəf cloner şablonudur və şablonun öz
sənədləri (INSPECTION_GUIDE, AGENTS.md) ingiliscədir — terminlər uyğun gəlsin
deyə eyni dildə yazılır. İstifadəçiyə ünvanlanan `EMR.md` isə azərbaycancadır.

**Ən vacib qayda:** statik analizlə tapılmayan heç nə uydurulmur. Tapılmayan hər
şey `NOT DETECTED` kimi işarələnir və brauzerdə yoxlanmaq üçün siyahıya düşür.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone

from ..config import ayarlar
from . import kontekst

log = logging.getLogger("saytlupa")

TAPILMADI = "NOT DETECTED — inspect in the browser (see INSPECTION_GUIDE.md)"

# Cloner şablonunun öz seçimləri (`AGENTS.md`-dən) — hədəf stek budur
HEDEF_STEK = [
    ("Framework", "Next.js 16 (App Router, React 19, TypeScript strict)"),
    ("UI kit", "shadcn/ui (Radix primitives)"),
    ("CSS", "Tailwind CSS v4 with oklch design tokens"),
    ("Icons", "Lucide React + extracted SVGs"),
    ("Deployment", "Vercel"),
]


# ------------------------------------------------------------- kiçik köməkçilər


def _cedvel(basliqlar: list[str], setirler: list[list[str]]) -> str:
    if not setirler:
        return f"_{TAPILMADI}_\n"
    xett = "| " + " | ".join(basliqlar) + " |"
    ayirici = "|" + "|".join("---" for _ in basliqlar) + "|"
    govde = ["| " + " | ".join(str(h) for h in s) + " |" for s in setirler]
    return "\n".join([xett, ayirici, *govde]) + "\n"


def _siyahi(deyerler: list[str]) -> str:
    return "\n".join(f"- {d}" for d in deyerler) + "\n" if deyerler else f"_{TAPILMADI}_\n"


def _yoxlanmali(deyerler: list[str]) -> str:
    return "\n".join(f"- [ ] {d}" for d in deyerler) + "\n"


def _basliq(ad: str, url: str) -> str:
    tarix = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return (
        f"# {ad}\n\n"
        f"> Auto-generated by **SaytLupa** — {tarix}\n"
        f"> Source: {url}\n"
        f"> Method: static analysis (HTML + CSS + DNS + headers). Anything that\n"
        f"> requires a rendered browser is marked `NOT DETECTED` — never guessed.\n\n"
    )


# ---------------------------------------------------------------- sənədlər


def _design_tokens(url: str, xam: dict) -> str:
    dizayn = kontekst.sahe(xam, "dizayn")
    sehife = kontekst.sahe(xam, "sehife")

    renqler = [
        [r.get("reng", ""), r.get("tekrar", 0)] for r in dizayn.get("esas_renqler", [])
    ]
    sriftler = [
        [s.get("ad", ""), s.get("tekrar", 0)] for s in dizayn.get("sriftler", [])
    ]

    return (
        _basliq("Design Tokens", url)
        + "## Colors\n\n"
        "Ranked by how often each value appears in the HTML and stylesheets.\n"
        "Pure black/white are filtered out. **Semantic roles (background, text,\n"
        "accent, border, error…) are NOT determined by static analysis** — assign\n"
        "them while looking at the rendered page.\n\n"
        + _cedvel(["Color", "Occurrences"], renqler)
        + f"\nTotal distinct colors found: {dizayn.get('reng_sayi', 0)}\n"
        "\n## Typography\n\n"
        "### Font families used by the site\n\n"
        + _cedvel(["Font", "Occurrences"], sriftler)
        + "\n### Fallback stacks referenced\n\n"
        + _siyahi(dizayn.get("ehtiyat_sriftler", []))
        + "\n### Google Fonts\n\n"
        + _siyahi(dizayn.get("google_sriftler", []))
        + "\n### Sizes, weights, line heights\n\n"
        f"_{TAPILMADI}_\n"
        "\n## Not detectable without a rendered browser\n\n"
        + _yoxlanmali(
            [
                "Spacing scale (padding/margin steps: 4/8/12/16/24/32…)",
                "Border radius per element (buttons, cards, inputs, avatars)",
                "Shadows / elevation (cards, dropdowns, modal overlay)",
                "Breakpoints — where the layout actually shifts",
                "Icon library and icon sizes",
                "Button variants (primary, secondary, ghost, icon-only, danger)",
                "Input styles (text, textarea, select, checkbox, toggle)",
                "Dark mode variants",
            ]
        )
        + "\n## CSS delivery (measured)\n\n"
        + _cedvel(
            ["Metric", "Value"],
            [
                ["Stylesheet files", dizayn.get("css_fayl_sayi", 0)],
                ["External CSS size", f"{dizayn.get('xarici_css_kb', 0)} KB"],
                ["Inline `<style>` size", f"{dizayn.get('daxili_css_kb', 0)} KB"],
                ["Viewport meta", sehife.get("viewport") or "—"],
            ],
        )
    )


def _component_inventory(url: str, xam: dict, sehifeler: list[dict]) -> str:
    sehife = kontekst.sahe(xam, "sehife")
    sayilar = sehife.get("basliq_saylari", {}) or {}
    sosial = sehife.get("sosial_linkler", {}) or {}

    olculen = [
        ["Forms", sehife.get("form_sayi", 0)],
        ["Images", sehife.get("sekil_sayi", 0)],
        ["Scripts", sehife.get("skript_sayi", 0)],
        ["H1", sayilar.get("h1", 0)],
        ["H2", sayilar.get("h2", 0)],
        ["H3", sayilar.get("h3", 0)],
        ["Internal links", sehife.get("daxili_link_sayi", 0)],
        ["External links", sehife.get("xarici_link_sayi", 0)],
    ]

    return (
        _basliq("Component Inventory", url)
        + "## Counted on the home page\n\n"
        "These are element counts, not components. They tell you how much there is\n"
        "to build, not what it looks like.\n\n"
        + _cedvel(["Element", "Count"], olculen)
        + "\n## Real content found (use this, not placeholders)\n\n"
        "### Headings (H1)\n\n"
        + _siyahi(sehife.get("h1_metnler", []))
        + "\n### Social links\n\n"
        + _siyahi([f"{ad}: {link}" for ad, link in sosial.items()])
        + "\n### Contact\n\n"
        + _siyahi(
            list(sehife.get("epostalar", [])) + list(sehife.get("telefonlar", []))
        )
        + "\n### Crawled pages (content is available in SaytLupa's RAG store)\n\n"
        + _cedvel(
            ["Title", "URL", "Text length"],
            [
                [s["basliq"] or "—", s["url"], len(s["metn"])]
                for s in sehifeler[:15]
            ],
        )
        + "\n## Components to document in the browser\n\n"
        + _yoxlanmali(
            [
                "Navigation (top bar / sidebar / mobile menu)",
                "Cards and list items",
                "Buttons and links — every variant and state",
                "Forms and inputs — validation and error states",
                "Modals, dropdowns, tabs, tooltips",
                "Avatars, badges, loading skeletons, toasts",
                "Empty states and error states",
                "Hover / focus / active / disabled states",
                "Responsive behaviour of each component",
            ]
        )
    )


def _layout_architecture(url: str, xam: dict, sehifeler: list[dict]) -> str:
    sehife = kontekst.sahe(xam, "sehife")

    return (
        _basliq("Layout Architecture", url)
        + "## Measured\n\n"
        + _cedvel(
            ["Property", "Value"],
            [
                ["Mobile viewport meta", "yes" if sehife.get("mobil_uygun") else "NO"],
                ["Viewport value", sehife.get("viewport") or "—"],
                ["HTML `lang`", sehife.get("dil") or "NOT SET"],
                ["Home page HTML size", f"{sehife.get('html_olcusu_kb', 0)} KB"],
                ["Pages crawled", xam.get("sehife_sayi", 0)],
            ],
        )
        + "\n## Site structure (crawled URLs)\n\n"
        + _siyahi([s["url"] for s in sehifeler[:20]])
        + "\n## Top internal links from the home page\n\n"
        + _siyahi(list(sehife.get("daxili_linkler", []))[:25])
        + "\n## Not detectable without a rendered browser\n\n"
        + _yoxlanmali(
            [
                "Grid system — CSS Grid, Flexbox or fixed widths",
                "Column count at each breakpoint",
                "Main content max-width",
                "Sticky elements (header, sidebar, floating buttons)",
                "Z-index layers",
                "Scroll behaviour (pagination, infinite scroll, virtual list)",
            ]
        )
    )


def _interaction_patterns(url: str, xam: dict) -> str:
    texno = kontekst.sahe(xam, "texnologiya")
    reklam = kontekst.sahe(xam, "reklam")
    tapilanlar = texno.get("texnologiyalar", []) or []

    return (
        _basliq("Interaction Patterns", url)
        + "## Libraries detected in the page source\n\n"
        "Only the presence of a library is detectable statically — how it is used\n"
        "(which animations, which transitions) is not.\n\n"
        + _siyahi(tapilanlar)
        + "\n## Analytics / tracking (affects observable interactions)\n\n"
        + _siyahi([a.get("ad", "") for a in reklam.get("aletler", [])])
        + "\n## Must be recorded in the browser\n\n"
        + _yoxlanmali(
            [
                "Hover, focus, active and disabled states",
                "Page and element entrance/exit transitions",
                "Menu / modal / dropdown open-close animation and duration",
                "Scroll-triggered effects (sticky header, reveal, parallax)",
                "Loading and skeleton states",
                "Form validation feedback and timing",
                "Keyboard navigation and focus rings",
                "`prefers-reduced-motion` handling",
            ]
        )
    )


def _tech_stack(url: str, xam: dict) -> str:
    texno = kontekst.sahe(xam, "texnologiya")
    dns = kontekst.sahe(xam, "dns")
    geo = kontekst.sahe(xam, "geo")
    sert = kontekst.sahe(xam, "sertifikat")
    dizayn = kontekst.sahe(xam, "dizayn")
    oz_olcme = (kontekst.sahe(xam, "surat") or {}).get("oz_olcme", {}) or {}

    olculen = [
        ["Detected technologies", ", ".join(texno.get("texnologiyalar", [])) or "—"],
        ["Server software", texno.get("server") or "—"],
        ["X-Powered-By", texno.get("guclendirici") or "—"],
        ["CDN", dns.get("cdn") or "none detected"],
        ["Hosting country / city", f"{geo.get('olke', '—')} / {geo.get('seher', '—')}"],
        ["Hosting provider", geo.get("provayder") or "—"],
        ["TLS", f"{sert.get('veren', '—')}, {sert.get('protokol', '—')}"],
        ["Google Fonts", ", ".join(dizayn.get("google_sriftler", [])) or "none"],
        ["Compression", oz_olcme.get("sixilma") or "—"],
        [
            "Lazy-loaded images",
            f"{oz_olcme.get('lazy_sekil_sayi', 0)} / {oz_olcme.get('sekil_sayi', 0)}",
        ],
        ["Home page load (own measurement)", f"{oz_olcme.get('yuklenme_saniye', '—')} s"],
    ]

    return (
        _basliq("Tech Stack Analysis", url)
        + "## What the target site uses (measured)\n\n"
        + _cedvel(["Item", "Value"], olculen)
        + "\n## Not detectable without DevTools\n\n"
        + _yoxlanmali(
            [
                "State management (Redux, Zustand, Pinia, React Query)",
                "API pattern — REST vs GraphQL (watch the network tab)",
                "CSS approach — Tailwind, CSS Modules, styled-components, vanilla",
                "Image strategy — CDN, srcset, WebP/AVIF",
                "Animation library actually in use",
            ]
        )
        + "\n## Our chosen equivalents (from the cloner template)\n\n"
        + _cedvel(["Layer", "Choice"], [[a, b] for a, b in HEDEF_STEK])
    )


def _emr(url: str, qovluq_yolu: str) -> str:
    """İstifadəçiyə ünvanlanan addımlar — azərbaycanca."""
    hedef = ayarlar.cloner_yolu or r"<ai-website-cloner qovluğunun yolu>"
    return (
        "# Klon üçün hazırdır\n\n"
        f"Mənbə sayt: **{url}**\n\n"
        "SaytLupa `ai-website-cloner` şablonunun gözlədiyi 5 araşdırma sənədini\n"
        "yazdı. Klonu skill özü qurur — aşağıdakı iki addımı at.\n\n"
        "## 1. Sənədləri şablona köçür\n\n"
        "```powershell\n"
        f'xcopy /E /I /Y "{qovluq_yolu}\\docs" "{hedef}\\docs"\n'
        "```\n\n"
        "## 2. Claude Code-da klonu başlat\n\n"
        "```\n"
        f"/clone-website {url}\n"
        "```\n\n"
        "## Nə hazırdır, nə yox\n\n"
        "| Sənəd | Vəziyyət |\n"
        "|---|---|\n"
        "| `DESIGN_TOKENS.md` | rənglər və şriftlər **ölçülüb**; boşluq, radius, kölgə brauzerdə yoxlanmalıdır |\n"
        "| `TECH_STACK_ANALYSIS.md` | server, CDN, texnologiyalar **ölçülüb** |\n"
        "| `COMPONENT_INVENTORY.md` | element sayları və real məzmun **var**; komponent variantları yoxlanmalıdır |\n"
        "| `LAYOUT_ARCHITECTURE.md` | səhifə siyahısı **var**; grid və breakpoint-lər yoxlanmalıdır |\n"
        "| `INTERACTION_PATTERNS.md` | yalnız kitabxanalar tapılıb; animasiyalar brauzerdə yazılmalıdır |\n\n"
        "Sənədlərdə `NOT DETECTED` yazılan hər şey **uydurulmayıb** — statik\n"
        "analizlə tapıla bilməyən məlumatdır. Skill onları brauzerdə özü toplayır.\n\n"
        "## Etik qeyd\n\n"
        "Klonlama öyrənmə və ilham üçündür. Başqasının məzmununu, loqosunu və\n"
        "brendini olduğu kimi yayımlamaq müəllif hüququnun pozulmasıdır.\n"
    )


# ------------------------------------------------------------------ giriş nöqtəsi


def senedler(url: str, xam: dict, sehifeler: list[dict]) -> dict[str, str]:
    """Yazılacaq sənədlər: {nisbi yol: məzmun}. Fayl sisteminə toxunmur."""
    return {
        "docs/research/DESIGN_TOKENS.md": _design_tokens(url, xam),
        "docs/research/COMPONENT_INVENTORY.md": _component_inventory(url, xam, sehifeler),
        "docs/research/LAYOUT_ARCHITECTURE.md": _layout_architecture(url, xam, sehifeler),
        "docs/research/INTERACTION_PATTERNS.md": _interaction_patterns(url, xam),
        "docs/research/TECH_STACK_ANALYSIS.md": _tech_stack(url, xam),
    }


def hazirla(analiz_id: int) -> dict:
    """Sənədləri `storage/klon/<domain>/` altında yazır və hazır əmri qaytarır."""
    k = kontekst.konteks(analiz_id)
    if k is None:
        return {"ugurlu": False, "tapilmadi": True, "sebeb": "Belə analiz yoxdur"}

    kok = kontekst.qovluq("klon", k["domain"])
    yazilanlar = senedler(k["url"], k["xam"], k["sehifeler"])
    yazilanlar["EMR.md"] = _emr(k["url"], str(kok))

    for nisbi, mezmun in yazilanlar.items():
        yol = kok / nisbi
        yol.parent.mkdir(parents=True, exist_ok=True)
        yol.write_text(mezmun, encoding="utf-8")

    # Köhnə ZIP qalsa istifadəçi yeni sənədləri yox, keçən dəfəkiləri yükləyər
    kohne_zip = kok.with_suffix(".zip")
    kohne_zip.unlink(missing_ok=True)

    log.info("Klon sənədləri yazıldı: %s (%s fayl)", kok, len(yazilanlar))
    return {
        "ugurlu": True,
        "qovluq": str(kok),
        "fayllar": sorted(yazilanlar),
        "emr": f"/clone-website {k['url']}",
        "cloner_yolu": ayarlar.cloner_yolu,
        "yukle_url": f"/api/analyze/{analiz_id}/yukle/klon",
    }
